#!/usr/bin/env python3
"""Build vps_resync.sh: push the current repository copies to the test VPS and
bring the already-deployed engine config up to the current generator's shape.

Why this exists: reality.sh regenerates /opt/reality/engine.conf on the next
run, so a box deployed from an older revision keeps an older config until then.
This payload syncs the script and applies the same shape to the live file, with
a real-start rehearsal before the container is restarted.

Usage:
  python .workbuddy/tools/build_vps_resync_payload.py
  SSH_TEST_PW=... python .workbuddy/tools/vps_ssh_run.py --host <ip> --proxy <p> \
      --file .workbuddy/tools/vps_resync.sh --timeout 900
"""
import base64
import pathlib

TOOLS = pathlib.Path(__file__).resolve().parent
ROOT = TOOLS.parents[1]
OUT = TOOLS / "vps_resync.sh"

SB_IMAGE = "ghcr.io/sagernet/sing-box:v1.14.1"
PY_IMAGE = "python:3.14-alpine"

reality_b64 = base64.b64encode((ROOT / "reality.sh").read_bytes()).decode()

TEMPLATE = r'''#!/usr/bin/env bash
# Generated by .workbuddy/tools/build_vps_resync_payload.py - do not edit.
set -u
CFG=/opt/reality
IMG=@@SB_IMAGE@@
PYIMG=@@PY_IMAGE@@
TS=$(date +%Y%m%d-%H%M%S)

echo "########## 1. 同步 reality.sh ##########"
md5sum "${CFG}/reality.sh" 2>/dev/null | sed 's/^/  改前 md5: /'
cp -a "${CFG}/reality.sh" "${CFG}/reality.sh.bak-${TS}" && echo "  备份 -> reality.sh.bak-${TS}"
base64 -d > /tmp/reality.sh.new <<'B64EOF'
@@REALITY_B64@@
B64EOF
echo "  落地大小: $(wc -c < /tmp/reality.sh.new) 字节（期望 @@REALITY_SIZE@@）"
bash -n /tmp/reality.sh.new && echo "  bash -n OK" || { echo "  !! 语法错误，放弃"; exit 1; }
chmod 755 /tmp/reality.sh.new
mv /tmp/reality.sh.new "${CFG}/reality.sh"
md5sum "${CFG}/reality.sh" | sed 's/^/  改后 md5: /'

echo
echo "########## 2. 把 engine.conf 对齐到当前生成器的形态 ##########"
cp -a "${CFG}/engine.conf" "${CFG}/engine.conf.bak-${TS}" && echo "  备份 -> engine.conf.bak-${TS}"
PROG='import sys, json
d = json.load(sys.stdin)
d["http_clients"] = [{"tag": "internet"}]
d["route"]["default_http_client"] = "internet"
for r in d["route"].get("rule_set", []):
    r["http_client"] = "internet"
json.dump(d, sys.stdout, indent=2)
sys.stdout.write("\n")'
docker run --rm -i "${PYIMG}" python -c "${PROG}" < "${CFG}/engine.conf" > /tmp/engine.conf.new || { echo "  !! 转换失败"; exit 1; }
CHECK='import sys, json
d = json.load(sys.stdin)
hc = d.get("http_clients")
assert hc == [{"tag": "internet"}], hc
assert d["route"].get("default_http_client") == "internet"
cl = [r.get("http_client") for r in d["route"]["rule_set"]]
assert cl == ["internet"] * len(cl), cl
assert "detour" not in json.dumps(hc)
print("  JSON 合法；http_clients 无 detour；default_http_client 已设；rule_set x%d 已引用" % len(cl))'
docker run --rm -i "${PYIMG}" python -c "${CHECK}" < /tmp/engine.conf.new || { echo "  !! 断言未过，放弃"; exit 1; }
cp /tmp/engine.conf.new "${CFG}/engine.conf"

echo
echo "########## 3. key 路径清单（不含任何值，用于与本地生成器对比）##########"
PATHS='import sys, json
def walk(o, p=""):
    if isinstance(o, dict):
        for k, v in o.items():
            yield from walk(v, (p + "." + k) if p else k)
    elif isinstance(o, list):
        for i, v in enumerate(o):
            yield from walk(v, "%s[%d]" % (p, i))
    else:
        yield p
d = json.load(sys.stdin)
print("\n".join(sorted(walk(d))))'
docker run --rm -i "${PYIMG}" python -c "${PATHS}" < "${CFG}/engine.conf"

echo
echo "########## 4. 真实启动预演（配置原样，仅换端口避开线上 8443）##########"
sed 's/"listen_port": 8443/"listen_port": 18443/' "${CFG}/engine.conf" > /tmp/engprobe.json
out=$(timeout 30 docker run --rm -v /tmp/engprobe.json:/etc/sing-box/config.json:ro "${IMG}" run -c /etc/sing-box/config.json 2>&1); rc=$?
echo "  rc=${rc}（124 = 存活满 30 秒即成功）"
echo "  告警/错误条数: $(printf '%s' "${out}" | grep -cE 'WARN|FATAL|ERROR')"
printf '%s\n' "${out}" | grep -E 'WARN|FATAL|ERROR' | head -3 | cut -c1-170 | sed 's/^/  | /'
rm -f /tmp/engprobe.json

echo
echo "########## 5. 重启并验证 ##########"
docker restart reality-engine-1 >/dev/null 2>&1 && echo "  已重启"
sleep 25
docker inspect reality-engine-1 --format '  status={{.State.Status}} exit={{.State.ExitCode}}'
echo "  启动后日志:"
docker logs --tail 4 reality-engine-1 2>&1 | cut -c1-170 | sed 's/^/  | /'
echo "  8443 监听条目: $(ss -ltn 2>/dev/null | grep -c ':8443 ')"
if timeout 8 bash -c 'cat < /dev/null > /dev/tcp/127.0.0.1/8443' 2>/dev/null; then
  echo "  8443 可连接 ✓"
else
  echo "  8443 不可连接 ✗"
fi
echo "RESULT: resync done"
'''

script = (
    TEMPLATE.replace("@@REALITY_B64@@", reality_b64)
    .replace("@@REALITY_SIZE@@", str((ROOT / "reality.sh").stat().st_size))
    .replace("@@SB_IMAGE@@", SB_IMAGE)
    .replace("@@PY_IMAGE@@", PY_IMAGE)
)
OUT.write_text(script, encoding="utf-8", newline="\n")
print(f"已生成 {OUT}（内嵌 reality.sh {len(reality_b64)} B base64，脚本 {OUT.stat().st_size} B）")
