#!/usr/bin/env python3
"""Build the payloads that push the current reality.sh to the test VPS.

Two modes, because the right thing to do depends on what changed:

  full   -- vps_deploy_install.sh
            back up the live files, install the new reality.sh, run a full
            default install with it (non-interactive), then verify that the
            credentials survived and the service came back healthy.

  script -- vps_sync_script.sh
            script-only. back up, install the new reality.sh, verify md5 and
            syntax, and check that the tgbot container sees the file through its
            bind mount. No installer run and no container restart: reality.sh is
            read by the operator and by tgbot, never baked into an image, so a
            restart would be pointless downtime.

Usage:
  python .workbuddy/tools/build_vps_deploy_payload.py [--mode full|script]
  SSH_TEST_PW=... python .workbuddy/tools/vps_ssh_run.py --host <ip> \
      --file .workbuddy/tools/vps_deploy_install.sh --timeout 900

Design notes (from the vps-remote-ops playbook):
  * no `set -e` in the payload -- one failed check must not abort the rest, or we
    end up with a half-cleaned box that is harder to reason about than a plain
    failure. Failures accumulate in FAILURES[] and are reported at the end.
  * config + users carry the private key and the client UUIDs, so they are
    backed up with a sha256 manifest BEFORE anything is touched, and their
    sha256 is compared before/after the install -- they must not change.
"""
import argparse
import base64
import hashlib
import pathlib

TOOLS = pathlib.Path(__file__).resolve().parent
ROOT = TOOLS.parents[1]

FULL = r'''#!/usr/bin/env bash
# Generated by .workbuddy/tools/build_vps_deploy_payload.py --mode full - do not edit.
set -u
CFG=/opt/reality
TS=$(date +%Y%m%d-%H%M%S)
BAK="/root/reality-deploy-${TS}"
FAILURES=()

step() { echo; echo "########## $* ##########"; }
bad()  { echo "  !! $*"; FAILURES+=("$*"); }

step "1. 备份现状（含凭据，先算 sha256 清单）"
mkdir -p "${BAK}"
for f in reality.sh config users engine.conf docker-compose.yml; do
  if [ -e "${CFG}/${f}" ]; then
    cp -a "${CFG}/${f}" "${BAK}/${f}" && echo "  备份 ${f}"
  else
    echo "  (${f} 不存在，跳过)"
  fi
done
cp -a "${CFG}/tgbot" "${BAK}/tgbot" 2>/dev/null && echo "  备份 tgbot/"
( cd "${BAK}" && find . -type f -exec sha256sum {} + | sort -k2 > SHA256SUMS )
echo "  备份目录: ${BAK}"
echo "  --- 清单 ---"
sed 's/^/  /' "${BAK}/SHA256SUMS"

echo
echo "  --- 改前指纹 ---"
echo "  reality.sh md5 : $(md5sum "${CFG}/reality.sh" | cut -d' ' -f1)"
echo "  config sha256  : $(sha256sum "${CFG}/config" | cut -c1-32)"
echo "  users  sha256  : $(sha256sum "${CFG}/users"  | cut -c1-32)"
BEFORE_CONFIG=$(sha256sum "${CFG}/config" | cut -d' ' -f1)
BEFORE_USERS=$(sha256sum "${CFG}/users"  | cut -d' ' -f1)

step "2. 落地新版 reality.sh"
base64 -d > /tmp/reality.sh.new <<'B64EOF'
@@REALITY_B64@@
B64EOF
NEW_SIZE=$(wc -c < /tmp/reality.sh.new | tr -d ' ')
echo "  新文件大小: ${NEW_SIZE} 字节（期望 @@REALITY_SIZE@@）"
[ "${NEW_SIZE}" = "@@REALITY_SIZE@@" ] || bad "大小不符：${NEW_SIZE} != @@REALITY_SIZE@@"
NEW_MD5=$(md5sum /tmp/reality.sh.new | cut -d' ' -f1)
echo "  新文件 md5 : ${NEW_MD5}（期望 @@REALITY_MD5@@）"
[ "${NEW_MD5}" = "@@REALITY_MD5@@" ] || bad "md5 不符：${NEW_MD5}"
if bash -n /tmp/reality.sh.new; then echo "  bash -n OK"; else bad "新版语法错误"; fi
chmod 755 /tmp/reality.sh.new
mv /tmp/reality.sh.new "${CFG}/reality.sh"
echo "  就位 md5   : $(md5sum "${CFG}/reality.sh" | cut -d' ' -f1)"
echo "  新版特征   : whiptail 调用=$(grep -c 'whiptail' "${CFG}/reality.sh" || true)  ui_ 函数定义数=$(grep -c '^function ui_' "${CFG}/reality.sh" || true)"

step "3. 运行安装器（默认安装 = 不带参数，非交互）"
cd "${CFG}" || bad "cd ${CFG} 失败"
START=$(date +%s)
timeout 900 bash "${CFG}/reality.sh" > /tmp/install.out 2>&1
RC=$?
echo "  安装器退出码: ${RC}（0 = 成功，124 = 超时）"
echo "  耗时: $(( $(date +%s) - START )) 秒"
[ "${RC}" = "0" ] || bad "安装器退出码 ${RC}"
echo "  --- 输出最后 70 行 ---"
tail -70 /tmp/install.out | sed 's/^/  | /'

step "4. 凭据是否原样保留"
AFTER_CONFIG=$(sha256sum "${CFG}/config" | cut -d' ' -f1)
AFTER_USERS=$(sha256sum "${CFG}/users"  | cut -d' ' -f1)
echo "  config 前: ${BEFORE_CONFIG:0:32}"
echo "  config 后: ${AFTER_CONFIG:0:32}"
echo "  users  前: ${BEFORE_USERS:0:32}"
echo "  users  后: ${AFTER_USERS:0:32}"
[ "${BEFORE_CONFIG}" = "${AFTER_CONFIG}" ] && echo "  config 未变 OK" || bad "config 被改动"
[ "${BEFORE_USERS}" = "${AFTER_USERS}" ]   && echo "  users  未变 OK" || bad "users 被改动"

step "5. 独立状态核查"
sleep 8
echo "  --- 容器 ---"
docker ps -a --format '  {{.Names}}\t{{.Status}}\t{{.Image}}' | head -12
echo "  --- 引擎 ---"
docker inspect reality-engine-1 --format '  status={{.State.Status}} exit={{.State.ExitCode}} restarts={{.RestartCount}}' 2>/dev/null
echo "  --- 端口 ---"
ss -ltn 2>/dev/null | grep -E ':(80|8080|8443)\b' | awk '{print "  "$4}' | sort -u
echo "  --- 引擎最近日志（应无 FATAL）---"
docker logs --tail 8 reality-engine-1 2>&1 | sed -r 's/\x1b\[[0-9;]*m//g' | cut -c1-150 | sed 's/^/  | /'
FATAL=$(docker logs --tail 200 reality-engine-1 2>&1 | grep -c 'FATAL' || true)
echo "  最近 200 行里 FATAL 条数: ${FATAL}"
[ "${FATAL}" = "0" ] || bad "引擎日志出现 FATAL"

step "6. 打一个本地可取的凭据备份包"
tar czf "${BAK}.tgz" -C /root "$(basename "${BAK}")" 2>/dev/null && \
  echo "  已生成 ${BAK}.tgz（$(wc -c < "${BAK}.tgz") 字节）" || bad "打包备份失败"
echo "  BAKPATH=${BAK}.tgz"

echo
if [ ${#FAILURES[@]} -eq 0 ]; then
  echo "RESULT: deploy+install OK（无失败项）"
else
  echo "RESULT: deploy+install 有 ${#FAILURES[@]} 项失败:"
  for f in "${FAILURES[@]}"; do echo "  - ${f}"; done
fi
'''

SCRIPT_ONLY = r'''#!/usr/bin/env bash
# Generated by .workbuddy/tools/build_vps_deploy_payload.py --mode script - do not edit.
set -u
CFG=/opt/reality
TS=$(date +%Y%m%d-%H%M%S)
FAILURES=()
bad() { echo "  !! $*"; FAILURES+=("$*"); }

echo "########## 1. 改前指纹 ##########"
echo "  reality.sh md5 = $(md5sum "${CFG}/reality.sh" | cut -d' ' -f1)"
echo "  大小           = $(wc -c < "${CFG}/reality.sh") 字节"
echo "  旧版特征       = whiptail 调用=$(grep -c 'whiptail' "${CFG}/reality.sh" || true)  ui_ 函数定义数=$(grep -c '^function ui_' "${CFG}/reality.sh" || true)"
cp -a "${CFG}/reality.sh" "${CFG}/reality.sh.bak-${TS}" && echo "  备份 -> reality.sh.bak-${TS}"

echo
echo "########## 2. 落地新版 reality.sh ##########"
base64 -d > /tmp/reality.sh.new <<'B64EOF'
@@REALITY_B64@@
B64EOF
NEW_SIZE=$(wc -c < /tmp/reality.sh.new | tr -d ' ')
NEW_MD5=$(md5sum /tmp/reality.sh.new | cut -d' ' -f1)
echo "  新文件大小: ${NEW_SIZE} 字节（期望 @@REALITY_SIZE@@）"
[ "${NEW_SIZE}" = "@@REALITY_SIZE@@" ] || bad "大小不符：${NEW_SIZE}"
echo "  新文件 md5 : ${NEW_MD5}（期望 @@REALITY_MD5@@）"
[ "${NEW_MD5}" = "@@REALITY_MD5@@" ] || bad "md5 不符：${NEW_MD5}"
if bash -n /tmp/reality.sh.new; then echo "  bash -n OK"; else bad "新版语法错误"; fi
chmod 755 /tmp/reality.sh.new
mv /tmp/reality.sh.new "${CFG}/reality.sh"
PLACED=$(md5sum "${CFG}/reality.sh" | cut -d' ' -f1)
echo "  就位 md5   : ${PLACED}"
[ "${PLACED}" = "@@REALITY_MD5@@" ] || bad "就位后 md5 不符"
echo "  新版特征   : whiptail 调用=$(grep -c 'whiptail' "${CFG}/reality.sh" || true)  ui_ 函数定义数=$(grep -c '^function ui_' "${CFG}/reality.sh" || true)"
echo "  措辞残留   : 独立单词 TUI = $(grep -cw 'TUI' "${CFG}/reality.sh" || true)（TUIC 协议名不算）"

echo
echo "########## 3. 为什么不用重启容器 ##########"
echo "  reality.sh 只被运维本人和 tgbot 读取，没有任何镜像内置它。"
echo "  --- tgbot 容器是否通过 bind mount 看到该文件 ---"
docker inspect tgbot-tgbot-1 --format '{{range .Mounts}}{{.Source}} -> {{.Destination}}{{"\n"}}{{end}}' 2>/dev/null \
  | grep -i reality | sed 's/^/  /' || echo "  (未发现挂载，tgbot 可能用别的方式调用)"
echo "  --- 从容器内部核对同一文件 ---"
docker exec tgbot-tgbot-1 sh -c 'md5sum /opt/reality/reality.sh 2>/dev/null || echo 容器内读不到' 2>/dev/null | sed 's/^/  /'
echo "  --- 容器启动时间（不应因本次同步而改变）---"
printf '  engine started=%s\n  nginx  started=%s\n' \
  "$(docker inspect -f '{{.State.StartedAt}}' reality-engine-1 2>/dev/null)" \
  "$(docker inspect -f '{{.State.StartedAt}}' reality-nginx-1 2>/dev/null)"

echo
if [ ${#FAILURES[@]} -eq 0 ]; then
  echo "RESULT: script sync OK（无失败项）"
else
  echo "RESULT: script sync 有 ${#FAILURES[@]} 项失败:"
  for f in "${FAILURES[@]}"; do echo "  - ${f}"; done
fi
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--mode", choices=("full", "script"), default="full")
    args = ap.parse_args()

    data = (ROOT / "reality.sh").read_bytes()
    b64 = base64.b64encode(data).decode()
    md5 = hashlib.md5(data).hexdigest()

    if args.mode == "full":
        template, name = FULL, "vps_deploy_install.sh"
    else:
        template, name = SCRIPT_ONLY, "vps_sync_script.sh"

    out = TOOLS / name
    script = (template.replace("@@REALITY_B64@@", b64)
                      .replace("@@REALITY_SIZE@@", str(len(data)))
                      .replace("@@REALITY_MD5@@", md5))
    out.write_text(script, encoding="utf-8", newline="\n")
    print(f"[{args.mode}] 已生成 {out}")
    print(f"  内嵌 reality.sh: {len(data)} B, md5 {md5}, base64 {len(b64)} B")
    print(f"  脚本总大小: {out.stat().st_size} B")


if __name__ == "__main__":
    main()
